apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "census-maweb.fullname" . }}
  labels:
    {{- include "census-maweb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.maweb.autoscaling.enabled }}
  replicas: {{ .Values.maweb.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "census-maweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.maweb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "census-maweb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.maweb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "census-maweb.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.maweb.image.repository }}:{{ .Values.maweb.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.maweb.image.pullPolicy }}
          env:
           {{- if .Values.maweb.env }}
            {{- range $key, $value := .Values.maweb.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end -}}
            {{- end }}
          ports:
            - containerPort: 8080
          volumeMounts: 
          - mountPath: /usr/local/tomcat/classpath/ma-params
            name: config-pvc-ma-params
          resources:
            {{- toYaml .Values.maweb.resources | nindent 12 }}
      initContainers:
      - name: setup-configs
        args:
        - ' echo ''Setting configmaps''  && cp -n /tmp/configmapfolder/async.properties /usr/local/tomcat/classpath/ma-params/async.properties  
          && cp -n  /tmp/configmapfolder/default-options-config.json /usr/local/tomcat/classpath/ma-params/default-options-config.json
          && cp -n  /tmp/configmapfolder/ms-config.xml /usr/local/tomcat/classpath/ma-params/ms-config.xml
          && cp -n  /tmp/configmapfolder/authdb-config.xml /usr/local/tomcat/classpath/ma-params/authdb-config.xml'
        command:
        - sh
        - -c
        image: busybox:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/configmapfolder/
          name: config-props
        - mountPath: /usr/local/tomcat/classpath/ma-params
          name: config-pvc-ma-params
      volumes:      
      - name: config-props
        configMap:
          name: {{ include "census-maweb.configMapName" . }}
      - name: config-pvc-ma-params  
        persistentVolumeClaim:
          claimName: {{ include "census-maweb.pvc" . }}
      {{- with .Values.maweb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.maweb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.maweb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
