apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nsiws
  name: {{ include "census-nsiws.pvc" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi