apiVersion: v1
kind: Service
metadata:
  name: {{ include "census-maweb.fullname" . }}
  labels:
    {{- include "census-maweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.maweb.service.type }}
  ports:
    - port: {{ .Values.maweb.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "census-maweb.selectorLabels" . | nindent 4 }}
