{{- if .Values.nsiws.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "census-nsiws.serviceAccountName" . }}
  labels:
    {{- include "census-nsiws.labels" . | nindent 4 }}
  {{- with .Values.nsiws.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
