apiVersion: v1
kind: Service
metadata:
  name: {{ include "census-nsiws.fullname" . }}
  labels:
    {{- include "census-nsiws.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nsiws.service.type }}
  ports:
    - port: {{ .Values.nsiws.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "census-nsiws.selectorLabels" . | nindent 4 }}
