apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  application.yml: |-
    proxy:
      landing-page: {{ .Values.proxyConfig.landingPage }}
      container-backend: kubernetes
      container-log-path: ./shinyproxy-logs
      kubernetes:
        internal-networking: true
        namespace: {{ .Release.Namespace }}
      heartbeat-rate: {{ .Values.proxyConfig.heartbeatRate }}
      heartbeat-timeout: {{ .Values.proxyConfig.heartbeatTimeout }}
      port: {{ .Values.proxyConfig.port }}
      authentication: {{ .Values.proxyConfig.authentication }}
      specs:
      - id: {{ .Values.app.id }}
        display-name: {{ .Values.app.displayName }}
        description: {{ .Values.app.description }}
        container-image: {{ .Values.app.image }}
        container-cmd: {{- toYaml $.Values.app.cmd | nindent 8 }}
        access-groups: {{ .Values.app.accessGroups }}
