{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxyDeploy.replicaCount }}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.proxyDeploy.podAnnotations | nindent 8 }}
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: shinyproxy
          image: "{{ .Values.proxyDeploy.image.name }}:{{ .Values.proxyDeploy.image.tag }}"
          imagePullPolicy: {{ .Values.proxyDeploy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.proxyDeploy.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: shinyproxy
              mountPath: /opt/shinyproxy/application.yml
              subPath: application.yml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9090
            periodSeconds: 20
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9090
            periodSeconds: 20
            initialDelaySeconds: 2
          resources:
            {{- toYaml .Values.proxyDeploy.resources | nindent 12 }}
      volumes:
        - name: shinyproxy
          emptyDir: {}
        - name: app-conf
          configMap:
            name: app-config
        {{ if eq .Values.proxyConfig.authentication.type "openid" }}
        - name: oidc-secrets
          secret:
            secretName: {{ .Values.proxyConfig.authentication.openid.clientCredentialsSecretName }}
        {{ end }}
      {{ if eq .Values.proxyConfig.authentication.type "openid" }}
      initContainers:
        - name: init
          image: "alpine"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-conf
              mountPath: /etc/app-conf/application.yml
              subPath: application.yml
            - name: oidc-secrets
              mountPath: /etc/oidc-secrets
            - name: shinyproxy
              mountPath: /etc/merge-conf
          command:
            - sh
            - -c
            - |
              wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq &&\
                   chmod +x /usr/bin/yq
              
              CLIENT_ID=`cat /etc/oidc-secrets/client-id`
              CLIENT_SECRET=`cat /etc/oidc-secrets/client-secret`

              cp /etc/app-conf/application.yml /etc/merge-conf/application.yml
              yq -i e ".proxy.openid.client-id |= \"$CLIENT_ID\"" /etc/merge-conf/application.yml
              yq -i e ".proxy.openid.client-secret |= \"$CLIENT_SECRET\"" /etc/merge-conf/application.yml
      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.proxyDeploy.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.proxyDeploy.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.proxyDeploy.tolerations | nindent 8 }}
